# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5b2686d953024a59a514979055ea51c8b8bc1fca0ec5911731c6f8866070a895f99eb6b2bb3f88e79570baa21a3a71b94eca92ea4b2cb9860f66c30a048afa4

test:
  secret_key_base: d03987ef8f4dfcae5b77ed16456748d382aeeeebdf5cb483a23774fc6933b390d571b83d332d89a4e1285c471536bc15491d916d2f01e6daa42a60c0e2ebbf00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
